# Generated by Django 2.0.5 on 2018-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id_beneficio', models.IntegerField(db_column='ID_BENEFICIO', primary_key=True, serialize=False)),
                ('numero_cartao', models.BigIntegerField(db_column='NR_CARTAO')),
                ('saldo', models.DecimalField(db_column='VL_SALDO', decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'TB_BENEFICIO',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(db_column='ID_EMPRESA', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='DS_CNPJ', max_length=14)),
                ('razao_social', models.CharField(db_column='DS_RAZAO_SOCIAL', max_length=100)),
                ('logradouro', models.CharField(db_column='DS_ENDERECO_LOGRADOURO', max_length=100)),
                ('numero', models.IntegerField(db_column='NR_ENDERECO_NUMERO')),
                ('bairro', models.CharField(db_column='DS_ENDERECO_BAIRRO', max_length=40)),
                ('cidade', models.CharField(db_column='DS_ENDERECO_CIDADE', max_length=80)),
                ('estado', models.CharField(db_column='DS_ENDERECO_ESTADO', max_length=40)),
                ('cep', models.IntegerField(db_column='NR_ENDERECO_CEP')),
                ('telefone', models.CharField(db_column='DS_TELEFONE', max_length=14)),
            ],
            options={
                'db_table': 'TB_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.IntegerField(db_column='ID_FUNCIONARIO', primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_column='DS_CPF', max_length=11)),
                ('nome', models.CharField(db_column='DS_NOME', max_length=100)),
                ('sexo', models.CharField(db_column='DS_SEXO', max_length=10)),
                ('data_nascimento', models.DateTimeField(db_column='DT_NASCIMENTO')),
                ('logradouro', models.CharField(db_column='DS_ENDERECO_LOGRADOURO', max_length=100)),
                ('numero', models.IntegerField(db_column='NR_ENDERECO_NUMERO')),
                ('bairro', models.CharField(db_column='DS_ENDERECO_BAIRRO', max_length=40)),
                ('cidade', models.CharField(db_column='DS_ENDERECO_CIDADE', max_length=80)),
                ('estado', models.CharField(db_column='DS_ENDERECO_ESTADO', max_length=40)),
                ('cep', models.IntegerField(db_column='NR_ENDERECO_CEP')),
                ('telefone', models.CharField(db_column='DS_TELEFONE', max_length=14)),
                ('empresa', models.ForeignKey(db_column='ID_EMPRESA', on_delete='CASCADE', to='projeto.Empresa')),
            ],
            options={
                'db_table': 'TB_FUNCIONARIO',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id_tipo_beneficio', models.IntegerField(db_column='ID_TIPO_BENEFICIO', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='DS_TIPO_BENEFICIO', max_length=100)),
            ],
            options={
                'db_table': 'TB_TIPO_BENEFICIO',
            },
        ),
        migrations.AddField(
            model_name='beneficio',
            name='empresa',
            field=models.ForeignKey(db_column='ID_EMPRESA', on_delete='CASCADE', to='projeto.Empresa'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='funcionario',
            field=models.ForeignKey(db_column='ID_FUNCIONARIO', on_delete='CASCADE', to='projeto.Funcionario'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='tipo_beneficio',
            field=models.ForeignKey(db_column='ID_TIPO_BENEFICIO', on_delete='CASCADE', to='projeto.TipoBeneficio'),
        ),
    ]
